CREATE TABLE empresa (
    empresa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activa BOOLEAN NOT NULL,
    direccion VARCHAR(255),
    email_contacto VARCHAR(150),
    fecha_actualizacion TIMESTAMP,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_fin_plan DATE,
    fecha_inicio_plan DATE,
    max_activos INTEGER,
    max_usuarios INTEGER,
    nombre VARCHAR(150) NOT NULL,
    rut VARCHAR(20) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    tipo_plan VARCHAR(50) NOT NULL,
    CONSTRAINT chk_empresa_tipo_plan
        CHECK (tipo_plan IN ('FREE', 'BASICO', 'PROFESIONAL', 'ENTERPRISE')),
    demo BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE rol_usuario (
    rol_usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE permiso_usuario (
    rol_permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

CREATE TABLE rol_permiso (
    rol_usuario_id BIGINT NOT NULL,
    permiso_usuario_id BIGINT NOT NULL,

    PRIMARY KEY (rol_usuario_id, permiso_usuario_id),

    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (rol_usuario_id)
        REFERENCES rol_usuario(rol_usuario_id),

    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (permiso_usuario_id)
        REFERENCES permiso_usuario(rol_permiso_id)
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    fecha_bloqueo TIMESTAMP,
    intentos_fallidos INTEGER,
    nombre VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(50) NOT NULL,
    empresa_id BIGINT NOT NULL,

    CONSTRAINT chk_usuario_rol
        CHECK (rol IN (
            'SUPER_ADMIN',
            'ADMIN_EMPRESA',
            'JEFE_MANTENIMIENTO',
            'TECNICO',
            'BODEGUERO',
            'USUARIO'
        )),

    CONSTRAINT fk_usuario_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    contacto VARCHAR(150),
    email VARCHAR(150),
    nombre VARCHAR(150) NOT NULL,
    rut VARCHAR(20) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    tipo_proveedor VARCHAR(30),
    empresa_id BIGINT NOT NULL,

    CONSTRAINT chk_tipo_proveedor
        CHECK (tipo_proveedor IN (
            'INTERNO',
            'EXTERNO'
        )),

    CONSTRAINT fk_proveedor_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE ubicacion (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    descripcion TEXT,
    direccion VARCHAR(255),
    nombre VARCHAR(150) NOT NULL,
    empresa_id BIGINT NOT NULL,

    CONSTRAINT fk_ubicacion_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE tipo_activo (
    id_tipo_activo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    descripcion TEXT,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    vida_util_referencial_meses INTEGER NOT NULL,
    empresa_id BIGINT NOT NULL,

    CONSTRAINT fk_tipo_activo_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE activo (
    id_activo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_interno VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    estado_actual VARCHAR(50),
    fecha_adquisicion DATE NOT NULL,
    fecha_baja DATE,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    motivo_baja VARCHAR(255),
    nombre VARCHAR(150) NOT NULL,
    numero_serie VARCHAR(100),
    valor_adquisicion NUMERIC(38,2) NOT NULL,
    valor_residual NUMERIC(38,2) NOT NULL,
    vida_util_meses INTEGER NOT NULL,

    empresa_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    id_tipo_activo BIGINT NOT NULL,
    ubicacion_id BIGINT NOT NULL,

    CONSTRAINT chk_activo_estado
        CHECK (estado_actual IN (
            'OPERATIVO',
            'MANTENCION',
            'OBSOLETO',
            'BAJA',
            'FUERA_SERVICIO'
        )),

    CONSTRAINT fk_activo_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_activo_proveedor
        FOREIGN KEY (proveedor_id)
        REFERENCES proveedor(id_proveedor),

    CONSTRAINT fk_activo_tipo
        FOREIGN KEY (id_tipo_activo)
        REFERENCES tipo_activo(id_tipo_activo),

    CONSTRAINT fk_activo_ubicacion
        FOREIGN KEY (ubicacion_id)
        REFERENCES ubicacion(id_ubicacion)
);

CREATE TABLE bodega (
    id_bodega BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activa BOOLEAN NOT NULL,
    nombre VARCHAR(255),
    ubicacion_fisica VARCHAR(255),
    empresa_id BIGINT NOT NULL,

    CONSTRAINT fk_bodega_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE repuesto (
    id_repuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL,
    codigo VARCHAR(255) NOT NULL,
    costo_unitario NUMERIC(15,2) NOT NULL,
    descripcion TEXT,
    nombre VARCHAR(255) NOT NULL,
    stock_minimo INTEGER NOT NULL,
    empresa_id BIGINT NOT NULL,

    CONSTRAINT fk_repuesto_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE stock_repuesto (
    id_stock_repuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL,
    empresa_id BIGINT NOT NULL,
    id_bodega BIGINT NOT NULL,
    id_repuesto BIGINT NOT NULL,

    CONSTRAINT fk_stock_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_stock_bodega
        FOREIGN KEY (id_bodega)
        REFERENCES bodega(id_bodega),

    CONSTRAINT fk_stock_repuesto
        FOREIGN KEY (id_repuesto)
        REFERENCES repuesto(id_repuesto)
);

CREATE TABLE plan_mantenimiento (
    id_plan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT,
    esta_activo BOOLEAN NOT NULL,
    frecuencia_dias INTEGER NOT NULL,
    proxima_ejecucion TIMESTAMP,
    tipo_mantenimiento VARCHAR(50) NOT NULL,
    ultima_ejecucion TIMESTAMP,

    empresa_id BIGINT NOT NULL,
    id_activo BIGINT NOT NULL,

    CONSTRAINT chk_plan_tipo
        CHECK (tipo_mantenimiento IN (
            'PREVENTIVO',
            'CORRECTIVO',
            'PREDICTIVO'
        )),

    CONSTRAINT fk_plan_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_plan_activo
        FOREIGN KEY (id_activo)
        REFERENCES activo(id_activo)
);

CREATE TABLE orden_mantenimiento (
    id_orden BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    costo NUMERIC(15,2),
    duracion_segundos BIGINT,
    estado VARCHAR(50) NOT NULL,
    fecha_ejecucion TIMESTAMP,
    fecha_fin_ejecucion TIMESTAMP,
    fecha_programada TIMESTAMP NOT NULL,
    fecha_termino TIMESTAMP NOT NULL,
    observaciones VARCHAR(255),
    ruta_archivo VARCHAR(255),
    tipo_mantenimiento VARCHAR(50) NOT NULL,
    titulo VARCHAR(255),

    empresa_id BIGINT NOT NULL,
    id_activo BIGINT NOT NULL,
    id_plan BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_usuario_ejecucion BIGINT,
    id_usuario_finalizacion BIGINT,

    CONSTRAINT chk_orden_estado
        CHECK (estado IN (
            'PENDIENTE',
            'PROGRAMADA',
            'EN_EJECUCION',
            'COMPLETADA',
            'CANCELADA'
        )),

    CONSTRAINT chk_orden_tipo
        CHECK (tipo_mantenimiento IN (
            'PREVENTIVO',
            'CORRECTIVO',
            'PREDICTIVO'
        )),

    CONSTRAINT fk_orden_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_orden_activo
        FOREIGN KEY (id_activo)
        REFERENCES activo(id_activo),

    CONSTRAINT fk_orden_plan
        FOREIGN KEY (id_plan)
        REFERENCES plan_mantenimiento(id_plan),

    CONSTRAINT fk_orden_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_orden_usuario_ejecucion
        FOREIGN KEY (id_usuario_ejecucion)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_orden_usuario_finalizacion
        FOREIGN KEY (id_usuario_finalizacion)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE archivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    tipo VARCHAR(255),
    url VARCHAR(255),
    orden_id BIGINT,

    CONSTRAINT fk_archivo_orden
        FOREIGN KEY (orden_id)
        REFERENCES orden_mantenimiento(id_orden)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device VARCHAR(150),
    expiry_date TIMESTAMPTZ NOT NULL,
    ip VARCHAR(50),
    token VARCHAR(500) NOT NULL UNIQUE,

    empresa_id BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT fk_refresh_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_refresh_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP,
    token VARCHAR(255),
    used BOOLEAN NOT NULL,

    empresa_id BIGINT NOT NULL,
    user_id_usuario BIGINT,

    CONSTRAINT fk_password_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_password_usuario
        FOREIGN KEY (user_id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE depreciacion (
    id_depreciacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    metodo VARCHAR(255) NOT NULL,
    valor_inicial NUMERIC(15,2) NOT NULL,
    valor_residual NUMERIC(15,2) NOT NULL,
    vida_util_meses INTEGER NOT NULL,
    empresa_id BIGINT NOT NULL,
    id_activo BIGINT NOT NULL,
    CONSTRAINT depreciacion_metodo_check
    CHECK (
        metodo IN (
            'LINEA_RECTA',
            'SALDO_DECRECIENTE',
            'UNIDADES_PRODUCCION'
        )
    ),

    CONSTRAINT fk_depreciacion_empresa
    FOREIGN KEY (empresa_id)
    REFERENCES empresa(empresa_id),

    CONSTRAINT fk_depreciacion_activo
    FOREIGN KEY (id_activo)
    REFERENCES activo(id_activo)
);

CREATE TABLE public.depreciacion_mensual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    depreciacion_acumulada NUMERIC(38,2) NOT NULL,
    depreciacion_mensual NUMERIC(38,2) NOT NULL,
    fecha DATE NOT NULL,
    mes INTEGER NOT NULL,
    valor_contable NUMERIC(38,2) NOT NULL,

    empresa_id BIGINT NOT NULL,
    activo_id BIGINT NOT NULL,

    CONSTRAINT fk22osvoiix3demns2fcf9xqm1d
        FOREIGN KEY (activo_id)
        REFERENCES public.activo(id_activo),

    CONSTRAINT fk2ojekxq58wea2tol8n36jd79p
        FOREIGN KEY (empresa_id)
        REFERENCES public.empresa(empresa_id)
);

CREATE TABLE public.historial_estado_activo (
    id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comentario VARCHAR(255),
    estado VARCHAR(255) NOT NULL,
    fecha TIMESTAMP(6) NOT NULL,
    empresa_id BIGINT NOT NULL,
    id_activo BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT historial_estado_activo_estado_check
        CHECK (
            estado IN (
                'OPERATIVO',
                'MANTENCION',
                'OBSOLETO',
                'BAJA',
                'FUERA_SERVICIO'
            )
        ),

    CONSTRAINT fk4304dw3b5q90axf8gmjw6xexl
        FOREIGN KEY (id_activo)
        REFERENCES public.activo(id_activo),

    CONSTRAINT fkbd9dnd8onj3u03tm1kxwps1ll
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fklxc5f6oy5nvutyh2acgfu33ip
        FOREIGN KEY (empresa_id)
        REFERENCES public.empresa(empresa_id)
);

CREATE TABLE public.movimiento_inventario (
    id_movimiento_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cantidad INTEGER,
    fecha TIMESTAMP(6),
    motivo VARCHAR(255),
    referencia VARCHAR(255),
    stock_anterior INTEGER,
    stock_posterior INTEGER,
    tipo VARCHAR(255),

    empresa_id BIGINT NOT NULL,
    id_bodega BIGINT,
    id_stock_repuesto BIGINT NOT NULL,
    id_usuario BIGINT,

    CONSTRAINT movimiento_inventario_tipo_check
        CHECK (
            tipo IN (
                'ENTRADA',
                'SALIDA',
                'AJUSTE',
                'TRANSFERENCIA'
            )
        ),

    CONSTRAINT fk93w2jdh5db2ee213yhev288mq
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario),

    CONSTRAINT fkhaly85ah7e4om10ghwdu4bvpl
        FOREIGN KEY (id_stock_repuesto)
        REFERENCES public.repuesto(id_repuesto),

    CONSTRAINT fklmih61nlqedbs7h2uk4u7uykl
        FOREIGN KEY (empresa_id)
        REFERENCES public.empresa(empresa_id),

    CONSTRAINT fkqtpfh3ygrdle6ti0c0p3m8773
        FOREIGN KEY (id_bodega)
        REFERENCES public.bodega(id_bodega)
);

CREATE TABLE public.orden_reprogramacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fecha_anterior TIMESTAMP(6) NOT NULL,
    fecha_nueva TIMESTAMP(6) NOT NULL,
    motivo VARCHAR(255),

    empresa_id BIGINT NOT NULL,
    id_orden BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT fk2u681ttfcm2qq19gc4mo0hwp1
        FOREIGN KEY (id_orden)
        REFERENCES public.orden_mantenimiento(id_orden),

    CONSTRAINT fkjs5vvrvc9xiyu9qlw1m2uwe1k
        FOREIGN KEY (empresa_id)
        REFERENCES public.empresa(empresa_id),

    CONSTRAINT fks2btco4mh6t4f6dvahd2ucoq4
        FOREIGN KEY (id_usuario)
        REFERENCES public.usuario(id_usuario)
);

CREATE TABLE orden_repuesto (
    id_orden_repuesto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER,
    costo_total NUMERIC(38,2),
    costo_unitario NUMERIC(38,2),

    empresa_id BIGINT NOT NULL,
    id_orden BIGINT NOT NULL,
    id_repuesto BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,

    CONSTRAINT fk_orden_repuesto_orden
        FOREIGN KEY (id_orden)
        REFERENCES orden_mantenimiento(id_orden),

    CONSTRAINT fk_orden_repuesto_repuesto
        FOREIGN KEY (id_repuesto)
        REFERENCES repuesto(id_repuesto),

    CONSTRAINT fk_orden_repuesto_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    -- Falta esta FK en tu script original
    -- Si existe la columna id_usuario en la tabla usuario:
    
    CONSTRAINT fk_orden_repuesto_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);



