CREATE TABLE lectura_temperatura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperatura NUMERIC(6,2) NOT NULL,
    texto_ocr TEXT,
    fecha_lectura TIMESTAMP NOT NULL,
    empresa_id BIGINT NOT NULL,
    CONSTRAINT fk_lectura_temperatura_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresa(empresa_id)
);

CREATE INDEX idx_lectura_temperatura_empresa_fecha
    ON lectura_temperatura (empresa_id, fecha_lectura DESC);
