-- =====================================================================
-- Modulo "Control de Turno"
-- =====================================================================
-- Puntos de control (temperatura, humedad, setpoint, etc.) monitoreados
-- manualmente por los tecnicos en cada turno, y sus lecturas horarias.
-- Reemplaza el registro en planilla Excel
-- (Copia_de_SISTEMA_DE_CONTROL_DE_MANTENCION) por paneles graficos
-- dentro de svua (ver modulo cl.aracridav.svua.controlturno).

CREATE TABLE punto_control (
    id_punto_control BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    unidad VARCHAR(20) NOT NULL,
    valor_min NUMERIC(10,2),
    valor_max NUMERIC(10,2),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_punto_control_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE TABLE lectura_control (
    id_lectura_control BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    punto_control_id BIGINT NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    turno VARCHAR(20) NOT NULL,
    observacion TEXT,
    usuario_id BIGINT,
    empresa_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_lectura_control_punto
        FOREIGN KEY (punto_control_id)
        REFERENCES punto_control(id_punto_control),

    CONSTRAINT fk_lectura_control_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_lectura_control_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id)
);

CREATE INDEX idx_lectura_control_punto_fecha
    ON lectura_control(punto_control_id, fecha_hora);

-- ---------------------------------------------------------------------
-- Row Level Security: estas 2 tablas nuevas tienen empresa_id, asi que
-- (ver V27__enable_row_level_security_por_empresa.sql, seccion
-- "IMPORTANTE") hay que repetirles el mismo patron ENABLE + FORCE +
-- CREATE POLICY manualmente, porque V27 solo corrio una vez sobre las
-- tablas que existian en ese momento.
-- ---------------------------------------------------------------------
DO $$
DECLARE
    tabla text;
BEGIN
    FOREACH tabla IN ARRAY ARRAY['punto_control', 'lectura_control']
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tabla);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tabla);

        EXECUTE format('DROP POLICY IF EXISTS empresa_isolation ON %I', tabla);

        EXECUTE format(
            'CREATE POLICY empresa_isolation ON %I
                USING (
                    current_setting(''app.bypass_rls'', true) = ''on''
                    OR empresa_id = NULLIF(current_setting(''app.current_empresa_id'', true), '''')::bigint
                )
                WITH CHECK (
                    current_setting(''app.bypass_rls'', true) = ''on''
                    OR empresa_id = NULLIF(current_setting(''app.current_empresa_id'', true), '''')::bigint
                )',
            tabla
        );
    END LOOP;
END $$;
