-- =====================================================================
-- Historial completo de cambios (Hibernate Envers)
-- =====================================================================
-- Complementa V29 (quien/cuando fue la ULTIMA modificacion de cada
-- fila). Esto guarda ademas CADA version anterior de cada fila, para
-- las entidades de negocio mas sensibles -- ver Usuario, Activo,
-- OrdenMantenimiento, OrdenReprogramacion, OrdenRepuesto, Repuesto,
-- StockRepuesto, Proveedor, Bodega, Ubicacion, TipoActivo y
-- MovimientoInventario (todas marcadas @Audited en su entidad Java).
--
-- No se incluyeron ADREDE: RefreshToken/PasswordResetToken (tokens de
-- seguridad efimeros, no aportan valor auditar su historico),
-- SesionUsuario/HistorialEstadoActivo (ya son ellos mismos un log/
-- historial, auditarlos seria un historial de un historial),
-- Notificacion, LecturaTemperatura y Depreciacion/DepreciacionMensual
-- (series de tiempo/calculos que se insertan una vez y no se
-- modifican). PuntoControl/LecturaControl (modulo Control de Turno)
-- quedaron pendientes en esta migracion: ese modulo vivia en la rama
-- "graficos" todavia no fusionada a esta rama al momento de escribir
-- esto. PuntoControl se agrego despues en V34, una vez fusionada.
--
-- Como funciona: Hibernate Envers (@Audited en cada entidad, ver
-- RevisionInfo/RevisionInfoListener) escribe automaticamente una fila
-- nueva en la <tabla>_aud correspondiente en CADA insert/update/delete,
-- ademas de la fila normal en la tabla real. No hace falta tocar el
-- codigo de los servicios: es transparente, Hibernate lo intercepta a
-- nivel de sesion.
--
-- revtype: 0 = ADD (fila creada), 1 = MOD (fila modificada),
--          2 = DEL (fila eliminada; las columnas de negocio quedan con
--          el ultimo valor conocido antes del DELETE).
--
-- Las FK de relacion (ej. id_tipo_activo en activo_aud) se guardan
-- como BIGINT simple, SIN constraint de FK: a proposito, para no
-- bloquear un DELETE en la tabla real solo porque una fila _aud
-- historica todavia "apunta" a algo que ya no existe (el historial
-- debe sobrevivir aunque el dato referenciado se borre despues).
--
-- Todas las tablas nuevas de esta migracion (revision_info y las 12
-- _aud) quedan CON Row Level Security, mismo patron que V27: aunque
-- alguna pantalla futura de "ver historial" se olvide de filtrar por
-- empresa, Postgres mismo no devuelve filas de otra empresa. Se aplica
-- al final de este archivo, una vez creadas todas las tablas.

CREATE TABLE revision_info (
    rev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT,
    usuario_id BIGINT,
    empresa_id BIGINT
);

CREATE INDEX idx_revision_info_empresa ON revision_info (empresa_id);
CREATE INDEX idx_revision_info_usuario ON revision_info (usuario_id);

-- ---------------------------------------------------------------------
-- usuario_aud
-- ---------------------------------------------------------------------
CREATE TABLE usuario_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_usuario BIGINT NOT NULL,

    nombre VARCHAR(150),
    rol VARCHAR(50),
    email VARCHAR(150),
    activo BOOLEAN,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_usuario)
);

-- ---------------------------------------------------------------------
-- activo_aud
-- ---------------------------------------------------------------------
CREATE TABLE activo_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_activo BIGINT NOT NULL,

    codigo_interno VARCHAR(50),
    nombre VARCHAR(150),
    descripcion TEXT,
    id_tipo_activo BIGINT,
    marca VARCHAR(100),
    modelo VARCHAR(100),
    numero_serie VARCHAR(100),
    fecha_adquisicion DATE,
    valor_adquisicion NUMERIC(15,2),
    valor_residual NUMERIC(15,2),
    vida_util_meses INTEGER,
    estado_actual VARCHAR(50),
    cuenta_contable VARCHAR(255),
    codigo_qr VARCHAR(150),
    codigo_ean13 VARCHAR(13),
    ubicacion_id BIGINT,
    proveedor_id BIGINT,
    fecha_baja DATE,
    motivo_baja VARCHAR(255),

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_activo)
);

-- ---------------------------------------------------------------------
-- orden_mantenimiento_aud
-- ---------------------------------------------------------------------
CREATE TABLE orden_mantenimiento_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_orden BIGINT NOT NULL,

    fecha_programada TIMESTAMP,
    fecha_termino TIMESTAMP,
    fecha_ejecucion TIMESTAMP,
    fecha_fin_ejecucion TIMESTAMP,
    duracion_segundos BIGINT,
    duracion_estimada_segundos BIGINT,
    tipo_mantenimiento VARCHAR(50),
    estado VARCHAR(50),
    titulo VARCHAR(255),
    observaciones VARCHAR(255),
    ruta_archivo VARCHAR(255),
    costo_total NUMERIC(15,2),
    id_proveedor BIGINT,
    horas_estimadas_proveedor NUMERIC(15,2),
    horas_reales_proveedor NUMERIC(15,2),
    valor_hora_proveedor NUMERIC(15,2),
    costo_mano_obra_estimadas_proveedor NUMERIC(15,2),
    costo_mano_obra_proveedor NUMERIC(15,2),
    notificacion_proveedor_enviada BOOLEAN,
    id_usuario_ejecucion BIGINT,
    id_usuario_pre_finalizacion BIGINT,
    id_usuario_finalizacion BIGINT,
    id_usuario BIGINT,
    id_activo BIGINT,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_orden)
);

-- ---------------------------------------------------------------------
-- orden_reprogramacion_aud
-- ---------------------------------------------------------------------
CREATE TABLE orden_reprogramacion_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id BIGINT NOT NULL,

    id_orden BIGINT,
    fecha_anterior TIMESTAMP,
    fecha_nueva TIMESTAMP,
    id_usuario BIGINT,
    motivo VARCHAR(255),

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id)
);

-- ---------------------------------------------------------------------
-- orden_repuesto_aud
-- ---------------------------------------------------------------------
CREATE TABLE orden_repuesto_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_orden_repuesto BIGINT NOT NULL,

    id_orden BIGINT,
    id_repuesto BIGINT,
    cantidad INTEGER,
    costo_unitario NUMERIC(38,2),
    costo_total NUMERIC(38,2),
    id_usuario BIGINT,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_orden_repuesto)
);

-- ---------------------------------------------------------------------
-- repuesto_aud
-- ---------------------------------------------------------------------
CREATE TABLE repuesto_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_repuesto BIGINT NOT NULL,

    version BIGINT,
    codigo VARCHAR(255),
    nombre VARCHAR(255),
    descripcion TEXT,
    costo_unitario NUMERIC(15,2),
    stock_actual INTEGER,
    stock_minimo INTEGER,
    activo BOOLEAN,
    tipo VARCHAR(50),
    cuenta_contable VARCHAR(255),

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_repuesto)
);

-- ---------------------------------------------------------------------
-- stock_repuesto_aud
-- ---------------------------------------------------------------------
CREATE TABLE stock_repuesto_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_stock_repuesto BIGINT NOT NULL,

    id_repuesto BIGINT,
    id_bodega BIGINT,
    cantidad INTEGER,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_stock_repuesto)
);

-- ---------------------------------------------------------------------
-- proveedor_aud
-- ---------------------------------------------------------------------
CREATE TABLE proveedor_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_proveedor BIGINT NOT NULL,

    nombre VARCHAR(150),
    rut VARCHAR(20),
    contacto VARCHAR(150),
    telefono VARCHAR(30),
    email VARCHAR(150),
    activo BOOLEAN,
    tipo_proveedor VARCHAR(30),

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_proveedor)
);

-- ---------------------------------------------------------------------
-- bodega_aud
-- ---------------------------------------------------------------------
CREATE TABLE bodega_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_bodega BIGINT NOT NULL,

    nombre VARCHAR(255),
    ubicacion_fisica VARCHAR(255),
    activa BOOLEAN,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_bodega)
);

-- ---------------------------------------------------------------------
-- ubicacion_aud
-- ---------------------------------------------------------------------
CREATE TABLE ubicacion_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_ubicacion BIGINT NOT NULL,

    nombre VARCHAR(150),
    descripcion TEXT,
    direccion VARCHAR(255),
    activo BOOLEAN,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_ubicacion)
);

-- ---------------------------------------------------------------------
-- tipo_activo_aud
-- ---------------------------------------------------------------------
CREATE TABLE tipo_activo_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_tipo_activo BIGINT NOT NULL,

    nombre VARCHAR(100),
    descripcion TEXT,
    vida_util_referencial_meses INTEGER,
    activo BOOLEAN,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_tipo_activo)
);

-- ---------------------------------------------------------------------
-- movimiento_inventario_aud
-- ---------------------------------------------------------------------
CREATE TABLE movimiento_inventario_aud (
    rev BIGINT NOT NULL REFERENCES revision_info (rev),
    revtype SMALLINT,
    id_movimiento_inventario BIGINT NOT NULL,

    id_stock_repuesto BIGINT,
    tipo VARCHAR(50),
    cantidad INTEGER,
    stock_anterior INTEGER,
    stock_posterior INTEGER,
    fecha TIMESTAMP,
    referencia VARCHAR(255),
    motivo VARCHAR(255),
    id_bodega BIGINT,
    id_usuario BIGINT,

    empresa_id BIGINT,
    fecha_creacion TIMESTAMP,
    creado_por_id BIGINT,
    fecha_modificacion TIMESTAMP,
    modificado_por_id BIGINT,

    PRIMARY KEY (rev, id_movimiento_inventario)
);


-- =====================================================================
-- Row Level Security para revision_info + las 12 tablas _aud nuevas
-- =====================================================================
-- Mismo patron que V27, pero acotado a las tablas de esta migracion
-- (V27 ya corrio antes y no vuelve a aplicarse retroactivamente a
-- tablas creadas despues). Si en el futuro se @Audited una entidad
-- nueva (fuera de esta migracion), hay que repetir este mismo patron
-- para su _aud puntual.
DO $$
DECLARE
    tabla text;
BEGIN
    FOR tabla IN
        SELECT DISTINCT c.table_name
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema
         AND t.table_name = c.table_name
         AND t.table_type = 'BASE TABLE'
        WHERE c.table_schema = 'public'
          AND c.column_name = 'empresa_id'
          AND (c.table_name = 'revision_info' OR c.table_name LIKE '%\_aud' ESCAPE '\')
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tabla);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tabla);

        EXECUTE format('DROP POLICY IF EXISTS empresa_isolation ON %I', tabla);

        EXECUTE format(
            'CREATE POLICY empresa_isolation ON %I
                USING (
                    current_setting(''app.bypass_rls'', true) = ''on''
                    OR empresa_id = NULLIF(current_setting(''app.current_empresa_id'', true), '''')::bigint
                )
                WITH CHECK (
                    current_setting(''app.bypass_rls'', true) = ''on''
                    OR empresa_id = NULLIF(current_setting(''app.current_empresa_id'', true), '''')::bigint
                )',
            tabla
        );
    END LOOP;
END $$;
