-- Mapea el codigo de un dispositivo fisico de monitoreo (ej. el
-- "Dispositivo: INS-877" que trae cada hoja de un reporte importado
-- por correo, ver CorreoLecturaImportador) a la empresa duena de ese
-- sensor. Necesario porque el correo que trae estos reportes lo envia
-- un proveedor externo (mismo remitente para todas las empresas), asi
-- que no se puede identificar la empresa por quien envia el correo --
-- solo por el dispositivo mismo, que es unico por sensor fisico.
CREATE TABLE dispositivo_empresa (
    id_dispositivo_empresa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_dispositivo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(150),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    empresa_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT now(),
    fecha_modificacion TIMESTAMP,
    creado_por_id BIGINT,
    modificado_por_id BIGINT,

    CONSTRAINT fk_dispositivo_empresa_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresa(empresa_id),

    CONSTRAINT fk_dispositivo_empresa_creado_por
        FOREIGN KEY (creado_por_id)
        REFERENCES usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT fk_dispositivo_empresa_modificado_por
        FOREIGN KEY (modificado_por_id)
        REFERENCES usuario(id_usuario)
        ON DELETE SET NULL,

    -- 🔒 El codigo de un sensor fisico es unico en el mundo real
    -- (numero de serie del fabricante): no deberia poder registrarse el
    -- mismo dos veces, ni siquiera en empresas distintas -- eso
    -- normalmente indicaria un error de tipeo, no un caso real.
    CONSTRAINT uq_dispositivo_empresa_codigo UNIQUE (codigo_dispositivo)
);

CREATE INDEX idx_dispositivo_empresa_empresa ON dispositivo_empresa (empresa_id);

-- Row Level Security: esta tabla es nueva, asi que V27 (que corrio una
-- sola vez sobre las tablas que existian en ese momento) no la cubrio
-- -- hay que repetirle el mismo patron manualmente (mismo criterio que
-- V29/V32/V34).
ALTER TABLE dispositivo_empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispositivo_empresa FORCE ROW LEVEL SECURITY;

CREATE POLICY empresa_isolation ON dispositivo_empresa
    USING (
        current_setting('app.bypass_rls', true) = 'on'
        OR empresa_id = NULLIF(current_setting('app.current_empresa_id', true), '')::bigint
    )
    WITH CHECK (
        current_setting('app.bypass_rls', true) = 'on'
        OR empresa_id = NULLIF(current_setting('app.current_empresa_id', true), '')::bigint
    );
