# 🔁 HTTP → HTTPS
server {
    listen 80;
    server_name svua.cl api.svua.cl;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
