server {
    listen 80;

    server_name svua.cl api.svua.cl;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}