version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: svua_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - svua_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build: ./svuaback
    container_name: svua_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOSTNAME: postgres
      DB_PORT: 5432
    expose:
      - "8080"   # 👈 SOLO interno
    networks:
      - svua_net

  frontend:
    build: ./frontend
    container_name: svua_frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "80"   # 👈 SOLO interno
    networks:
      - svua_net

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: svua_nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"     # panel admin
      - "443:443"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - svua_net

volumes:
  postgres_data:
  nginx_data:
  nginx_letsencrypt:

networks:
  svua_net:
    name: svua_net