spring.application.name=svuaback

# DB
spring.datasource.url=jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:svua}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# JWT (ahora configurable por entorno)
jwt.secret=${JWT_SECRET:ARACRIDAV_SVUA_586E3272357538782F413F4428472B4B6250655368566B597033733676397924}
jwt.expiration-token=${JWT_EXPIRATION_TOKEN:300000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

spring.http.converters.preferred-json-mapper=jackson2