name: Deploy SaaS

on:
  # Deshabilitar WorkFlow
  #workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |

            APP_DIR=svua/
            
            echo "📁 Verificando proyecto..."

            if [ ! -d "$APP_DIR/.git" ]; then
              echo "🚀 Primera instalación"

              git clone git@github.com:DaviSnake/svua.git $APP_DIR
            else
              echo "🔄 Actualizando proyecto"

              cd $APP_DIR
              git pull origin master
            fi

            cd $APP_DIR

            if [ ! -f ".env" ]; then

              echo "No existe"

            else
              echo "existe"

            fi

            echo "🐳 Levantando Docker"

            docker compose down
            docker compose up -d --build      
   

            echo "✅ Valida si existe certificado SSL "
            if [ ! -f "certbot/conf/renewal/svua.cl.conf" ]; then
            echo "🔐 Generando SSL..."

              docker compose run --rm --entrypoint certbot certbot certonly \
                --webroot \
                --webroot-path=/var/www/certbot \
                -d www.svua.cl -d svua.cl -d api.svua.cl \
                --email dmedina.c@hotmail.com \
                --agree-tos \
                --no-eff-email
            else
              echo "✅ SSL ya existe"
            fi

            echo "✅ Deploy completado"
